### ISSUE TITLE
APT repository is missing updated Debian/Ubuntu packages

### ISSUE THREAD

**Issue by gbw** [kanidm/kanidm#2987]
### I did this
```
# Followed https://kanidm.github.io/kanidm_ppa/
sudo apt update
sudo apt install kanidm 
```
### I expected the following
kanidm tools to be installed of latest nightly (1.4.0-dev as of date of issue creation).

### This happened instead
kanidm 1.3.0-dev is installed.

### Kanidm version details

- Output of `kanidm(d) version`: kanidm 1.3.0-dev
- Are you running it in a container? If so, which image/tag?: N/A
- If not a container, how'd you install it: apt
- Operating System / Version (On Unix please post the output of `uname -a`): `6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux`

**Comment by yaleman** [comment]
Should be fixed now, can you please check @gbw

**Comment by gbw** [comment]
Still out of date for me:
```
apt update
apt install kanidm
# kanidm is already the newest version (1:1.3.0~dev~202405170616+39ac38e).
```
Maybe it's caching, but `Packages.gz` still does not include a reference to 1.4.0-dev. Debugging:
```
curl -O https://kanidm.github.io/kanidm_ppa/debian/Packages.gz
gunzip Packages.gz
grep 1.4.0 Packages
```

**Comment by yaleman** [comment]
Ah, weird. Something blocked the push to github pages, I'll sort it.

**Comment by yaleman** [comment]
Try again please... cache seems to have cleared.

**Comment by gbw** [comment]
That worked. Thank you so much. Should I close the issue?

**Comment by yaleman** [comment]
Great to hear, thanks for reporting it
