### ISSUE TITLE
Trouble enrolling Yubikey through Chromium

### ISSUE THREAD

**Issue by fujexo** [kanidm/kanidm#4003]
### I did this

Add a new Passkey (Hardware, Yubikey 5 NFC) to my user

### I expected the following

Be able to add my Yubikey and then use that for logging in.

### This happened instead

Got an error that I cannot add my Yubikey:

```
a5fd853d-1af4-4f64-81ba-2c6d89b23552 INFO     request [ 1.80ms | 21.46% / 100.00% ] method: POST | uri: /ui/reset/add_passkey | version: HTTP/1.1 | connection_address: "10.89.12.1:34596" | client_address: "10.89.12.1" | latency: 1 | kopid: "a5fd853d-1af4-4f64-81ba-2c6d89b23552" | status_code: 200
a5fd853d-1af4-4f64-81ba-2c6d89b23552 INFO     ┝━ pre_validate_client_auth_info [ 1.30ms | 0.56% / 72.63% ]
a5fd853d-1af4-4f64-81ba-2c6d89b23552 INFO     │  ┕━ validate_client_auth_info_to_uat [ 1.29ms | 72.07% ]
a5fd853d-1af4-4f64-81ba-2c6d89b23552 INFO     ┕━ handle_idmcredentialupdate [ 106µs | 5.91% ]
1e5a351a-b8d8-4e4d-8c70-ec83337ae227 INFO     request [ 260µs | 100.00% ] method: POST | uri: /ui/api/finish_passkey | version: HTTP/1.1 | connection_address: "10.89.12.1:34596" | client_address: "10.89.12.1" | latency: 0 | kopid: "1e5a351a-b8d8-4e4d-8c70-ec83337ae227" | status_code: 422
1e5a351a-b8d8-4e4d-8c70-ec83337ae227 ERROR    ┕━ 🚨 [error]: Bad request for passkey creation: missing field `rk` at line 1 column 946
b364d708-63d9-4032-8536-d51d9ddc0f51 INFO     request [ 327µs | 100.00% ] method: GET | uri: /pkg/img/logo-square.svg?v=cHb51xfr | version: HTTP/1.1 | connection_address: "10.89.12.1:34596" | client_address: "10.89.12.1" | latency: 1 | kopid: "b364d708-63d9-4032-8536-d51d9ddc0f51" | status_code: 304
```

### Kanidm version details

- Output of `kanidm(d) version`: kanidmd 1.8.3
- Are you running it in a container? If so, which image/tag?: docker.io/kanidm/server:1.8.3
- Operating System / Version (On Unix please post the output of `uname -a`): Linux host.example.com 6.12.48+deb13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.48-1 (2025-09-20) x86_64 GNU/Linux
- Browser version: Chromium Version 142.0.7444.175 (Official Build) Arch Linux (64-bit). 

### Any other comments

It's working in Firefox 145.0.2 and also on Android Chrome. Sure looks like a Chromium only problem, but I guess I let you know anyway :)

**Comment by yaleman** [comment]
linking to #3969

**Comment by Firstyear** [comment]
Should be resolved in 1.8.4

**Comment by fujexo** [comment]
Unfortunately, it's still not working, I get the same error when adding a yubikey in Chrome.

```
6f30730f-81b5-4ede-9a50-ab71b4d1c7b7 INFO     request [ 1.80ms | 20.50% / 100.00% ] method: POST | uri: /ui/reset/add_passkey | version: HTTP/1.1 | connection_address: "10.89.12.1:59630" | client_address: "10.89.12.1" | latency: 1 | kopid: "6f30730f-81b5-4ede-9a50-ab71b4d1c7b7" | status_code: 200
6f30730f-81b5-4ede-9a50-ab71b4d1c7b7 INFO     ┝━ pre_validate_client_auth_info [ 1.33ms | 0.60% / 73.76% ]
6f30730f-81b5-4ede-9a50-ab71b4d1c7b7 INFO     │  ┕━ validate_client_auth_info_to_uat [ 1.32ms | 73.16% ]
6f30730f-81b5-4ede-9a50-ab71b4d1c7b7 INFO     ┕━ handle_idmcredentialupdate [ 104µs | 5.75% ]
740f723b-13dd-4bdb-b2f3-ccf82e97a050 INFO     request [ 228µs | 100.00% ] method: GET | uri: /pkg/img/favicon.png?v=b/QxIvv2 | version: HTTP/1.1 | connection_address: "10.89.12.1:59630" | client_address: "10.89.12.1" | latency: 0 | kopid: "740f723b-13dd-4bdb-b2f3-ccf82e97a050" | status_code: 304
c1f7905a-39e4-4a00-a567-a299c41d367f INFO     request [ 246µs | 100.00% ] method: POST | uri: /ui/api/finish_passkey | version: HTTP/1.1 | connection_address: "10.89.12.1:59630" | client_address: "10.89.12.1" | latency: 0 | kopid: "c1f7905a-39e4-4a00-a567-a299c41d367f" | status_code: 422
c1f7905a-39e4-4a00-a567-a299c41d367f ERROR    ┕━ 🚨 [error]: Bad request for passkey creation: missing field `rk` at line 1 column 798
3d1b99da-bd7d-488a-9e68-a3fbf2fbd362 INFO     request [ 219µs | 100.00% ] method: GET | uri: /pkg/img/logo-square.svg?v=b/QxIvv2 | version: HTTP/1.1 | connection_address: "10.89.12.1:59630" | client_address: "10.89.12.1" | latency: 0 | kopid: "3d1b99da-bd7d-488a-9e68-a3fbf2fbd362" | status_code: 304
```

**Comment by Firstyear** [comment]
I can reproduce too, seems there was a problem with the underlying webauthn library update. I'll have to re-release and do 1.8.5. I'm investigating another issue first though.

**Comment by Firstyear** [comment]
@fujexo Are you using a container image? Can I ask you to test a build to ensure you see it's resolved too? I can confirm it's resolved on my end but I want to be 100% sure before we do another release.

**Comment by fujexo** [comment]
@Firstyear Yes, deployed as a container. Happy to test, let me know which image to try?

**Comment by Firstyear** [comment]
Please test `kanidm/server:1.8.4-gh4003`

**Comment by fujexo** [comment]
@Firstyear Can confirm that this fixed the bug 👍

**Comment by Firstyear** [comment]
Thanks so much! I'm so sorry this happened and that our previous fix didn't work for you. Certainly not what we want to see around here. 

I'll release 1.8.5 soon, but in the mean time continue to run that image tag.

**Comment by fujexo** [comment]
No worries, things happen sometimes 😅 Glad we got it sorted, thanks for testing and fixing!
